[package]
name = "chess_engine"
version = "0.1.0"
edition = "2024"

[features]
default = []
ffi = []

[dependencies]
array-init = "2.1.0"
nohash-hasher = "0.2.0"
owo-colors = "4.2.1"
rand = "0.9.0"
rayon = "1.11.0"

[profile.release]
debug = "line-tables-only"
lto = "fat"
